version: '3'
services:
  hisense_ac:
     image: deiger/aircon:latest
     container_name: hisense_ac
     healthcheck:
       disable: true
     environment:
       - CONFIG_DIR=/config
       - OPTIONS_FILE=./options.json
     network_mode: host
     volumes:
       - /opt/hisense:/config
